// AUTO-GENERATED by Loclo on every spawn — do not edit.
// Each Loclo tool here calls back into the backend's tool bridge using the
// per-spawn token in LOCLO_TOOL_TOKEN. The token is short-lived and only
// valid for this specific opencode run.
import { tool } from '@opencode-ai/plugin';

export default tool({
  description: "Get recent HTTP requests from the user's app in LivePreview. Requires the monitoring script.",
  args: {
      method: tool.schema.string().optional().describe("Filter by HTTP method."),
      status: tool.schema.number().optional().describe("Filter by HTTP status code."),
      url_contains: tool.schema.string().optional().describe("Filter by URL substring."),
      limit: tool.schema.number().optional().describe("Max requests (default 20, max 100)."),
    },
  async execute(args: { method?: string; status?: number; url_contains?: string; limit?: number }) {
    const token = process.env.LOCLO_TOOL_TOKEN;
    if (!token) return 'Loclo tool bridge not initialized (no token).';
    try {
      const resp = await fetch("http://localhost:4001/api/internal/tool-bridge", {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ token, tool: "browser_network_requests", args: { method: args.method, status: args.status, url_contains: args.url_contains, limit: args.limit } }),
      });
      const data = await resp.json();
      if (data && typeof data.result === 'string') {
        // The bridge may return an image payload (e.g. capture_screenshot).
        // Since opencode's tool return is text-only, we encode both text and
        // image in a JSON structure that OpenCodeCliAdapter can parse.
        if (data.image && typeof data.image.base64 === 'string') {
          return JSON.stringify({
            content: [
              { type: 'text', text: data.result },
              { type: 'image', data: data.image.base64, mimeType: data.image.mediaType }
            ]
          });
        }
        return data.result;
      }
      // Log the unexpected payload for debugging
      const payloadSummary = JSON.stringify(data).slice(0, 200);
      return `Loclo tool bridge returned unexpected payload. Received: ${payloadSummary}... (HTTP ${resp.status})`;
    } catch (err) {
      return 'Loclo tool bridge error: ' + (err instanceof Error ? err.message : String(err));
    }
  },
});
