// AUTO-GENERATED by Loclo on every spawn — do not edit.
// Each Loclo tool here calls back into the backend's tool bridge using the
// per-spawn token in LOCLO_TOOL_TOKEN. The token is short-lived and only
// valid for this specific opencode run.
import { tool } from '@opencode-ai/plugin';

export default tool({
  description: "Get provisioning and runtime logs from cloud sandboxes (Daytona/E2B) for this session.",
  args: {
      sandbox_id: tool.schema.string().optional().describe("Specific sandbox id, or omit for all."),
      last: tool.schema.number().optional().describe("Max lines per sandbox (default 100, max 500)."),
      filter: tool.schema.string().optional().describe("Case-insensitive substring filter."),
    },
  async execute(args: { sandbox_id?: string; last?: number; filter?: string }) {
    const token = process.env.LOCLO_TOOL_TOKEN;
    if (!token) return 'Loclo tool bridge not initialized (no token).';
    try {
      const resp = await fetch("http://localhost:4001/api/internal/tool-bridge", {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ token, tool: "get_sandbox_logs", args: { sandbox_id: args.sandbox_id, last: args.last, filter: args.filter } }),
      });
      const data = await resp.json();
      if (data && typeof data.result === 'string') {
        // The bridge may return an image payload (e.g. capture_screenshot).
        // Since opencode's tool return is text-only, we encode both text and
        // image in a JSON structure that OpenCodeCliAdapter can parse.
        if (data.image && typeof data.image.base64 === 'string') {
          return JSON.stringify({
            content: [
              { type: 'text', text: data.result },
              { type: 'image', data: data.image.base64, mimeType: data.image.mediaType }
            ]
          });
        }
        return data.result;
      }
      // Log the unexpected payload for debugging
      const payloadSummary = JSON.stringify(data).slice(0, 200);
      return `Loclo tool bridge returned unexpected payload. Received: ${payloadSummary}... (HTTP ${resp.status})`;
    } catch (err) {
      return 'Loclo tool bridge error: ' + (err instanceof Error ? err.message : String(err));
    }
  },
});
