// AUTO-GENERATED by Loclo on every spawn — do not edit.
// Each Loclo tool here calls back into the backend's tool bridge using the
// per-spawn token in LOCLO_TOOL_TOKEN. The token is short-lived and only
// valid for this specific opencode run.
import { tool } from '@opencode-ai/plugin';

export default tool({
  description: "Wait for a selector to appear, disappear, or change visibility state in the Playwright browser.",
  args: {
      selector: tool.schema.string().describe("CSS selector to wait for."),
      timeout: tool.schema.number().optional().describe("Timeout in milliseconds (default 30000)."),
      state: tool.schema.string().optional().describe("State to wait for: attached, detached, visible (default), hidden."),
    },
  async execute(args: { selector: string; timeout?: number; state?: string }) {
    const token = process.env.LOCLO_TOOL_TOKEN;
    if (!token) return 'Loclo tool bridge not initialized (no token).';
    try {
      const resp = await fetch("http://localhost:4001/api/internal/tool-bridge", {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ token, tool: "playwright_wait_for", args: { selector: args.selector, timeout: args.timeout, state: args.state } }),
      });
      const data = await resp.json();
      if (data && typeof data.result === 'string') {
        // The bridge may return an image payload (e.g. capture_screenshot).
        // Since opencode's tool return is text-only, we encode both text and
        // image in a JSON structure that OpenCodeCliAdapter can parse.
        if (data.image && typeof data.image.base64 === 'string') {
          return JSON.stringify({
            content: [
              { type: 'text', text: data.result },
              { type: 'image', data: data.image.base64, mimeType: data.image.mediaType }
            ]
          });
        }
        return data.result;
      }
      // Log the unexpected payload for debugging
      const payloadSummary = JSON.stringify(data).slice(0, 200);
      return `Loclo tool bridge returned unexpected payload. Received: ${payloadSummary}... (HTTP ${resp.status})`;
    } catch (err) {
      return 'Loclo tool bridge error: ' + (err instanceof Error ? err.message : String(err));
    }
  },
});
